const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PRO_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const root=process.cwd();const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'}[path.extname(file)]||'application/octet-stream';res.setHeader('Content-Type',type);res.end(fs.readFileSync(file));}catch(e){res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,...(process.env.PRO_CHROMIUM_PATH?{executablePath:process.env.PRO_CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu']}:{} )});
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],alerts=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{if(d.type()==='alert')alerts.push(d.message());await d.accept(d.type()==='prompt'?'テスト保存':'');});
 try{
 for(const name of ['unit_maker','mission_maker','item_maker']){await page.goto(base+'/game/'+name+'.html');assert.equal(await page.evaluate(()=>!!window.__PRO_BOOT_FAILED),false);}
 await page.goto(base+'/game/combined_maker.html');await page.locator('#importMode').selectOption('replace');await page.locator('#importFiles').setInputFiles('game/samples/pro_115_feature_sample.js');await page.waitForFunction(()=>document.querySelector('#packId').value==='pro_115_demo');assert.equal(await page.locator('#download').isDisabled(),false);
 const tab=async t=>page.locator('#tabs').getByRole('button',{name:t,exact:true}).click();
 await tab('スキル');await page.locator('#records button').filter({hasText:'複合覚醒'}).first().click();assert(await page.locator('#form').textContent().then(t=>t.includes('複合スキル')));
 await page.locator('#form').getByLabel('名前',{exact:true}).fill('変更した覚醒');await tab('パック・出力');assert((await page.locator('#code').inputValue()).includes('変更した覚醒'));await page.getByRole('button',{name:'元に戻す',exact:true}).click();assert(!(await page.locator('#code').inputValue()).includes('変更した覚醒'));await page.getByRole('button',{name:'やり直す',exact:true}).click();assert((await page.locator('#code').inputValue()).includes('変更した覚醒'));
 await page.getByRole('button',{name:'名前を付けて編集時点を保存',exact:true}).click();assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('pro_maker_checkpoints_v1')).length===1));
 await tab('武装');await page.locator('#records button').filter({hasText:'高出力砲'}).first().click();assert((await page.locator('#form').textContent()).includes('段階変化ボス'));await page.getByRole('button',{name:'複製してこのデータだけ変更',exact:true}).first().click();assert((await page.locator('#editorTitle').textContent()).includes('専用'));
 await tab('ユニット');await page.locator('#records button').filter({hasText:'段階変化ボス'}).first().click();await page.locator('#steps button').last().click();const phase=page.locator('fieldset').filter({has:page.locator('legend').filter({hasText:'段階変化・変形'})}).first();assert.equal(await phase.getByLabel('段階名',{exact:true}).inputValue(),'装甲排除');
 await tab('ミッション');await page.locator('#records button').filter({hasText:'新機能デモ：選択と段階変化'}).first().click();await page.locator('#steps button').last().click();assert((await page.locator('#form').textContent()).includes('戦闘中イベント'));
 await tab('パック・出力');await page.getByRole('button',{name:'関係図と到達条件を確認',exact:true}).click();assert((await page.locator('#overview').textContent()).includes('ドロップ'));
 await page.goto(base+'/game/index.html');await page.evaluate(async data=>window.PROGame.importAnyFiles([{name:'demo.js',text:async()=>data}]),fs.readFileSync('game/samples/pro_115_feature_sample.js','utf8'));
 // Choose the demo mission and unit through their actual click handlers; flow sections may be hidden.
 await page.locator('#missionList .mission').filter({hasText:'新機能デモ：選択と段階変化'}).evaluate(e=>e.click());await page.locator('#unitList .unit').filter({hasText:'デモ隊員'}).evaluate(e=>e.click());
 assert.equal(await page.locator('#deployBtn').isDisabled(),false);await page.locator('#deployBtn').evaluate(e=>e.click());await page.locator('#storySkip').click();await page.locator('#storyText').getByRole('button',{name:'森へ進む'}).click();await page.locator('#storySkip').click();
 // Skip battle presentation, preserving combat, event and history processing.
 await page.locator('#skipBtn').evaluate(e=>e.click());if(await page.locator('#storyOverlay').isVisible())await page.locator('#storySkip').click();await page.waitForFunction(()=>document.querySelector('#resultTurns').textContent!=='--'&&document.querySelector('#proBattleHistory').textContent.includes('新機能デモ：選択と段階変化'),null,{timeout:30000});
 const save=await page.evaluate(()=>Object.keys(localStorage).map(k=>{try{return JSON.parse(localStorage.getItem(k));}catch(e){return null}}).find(x=>x?.battleHistory?.length));assert(save,'saved battle history');assert.equal(save.campaignFlags.demo_forest,true);assert(save.battleHistory[0].timeline.length>0);assert(save.battleHistory[0].timeline.some(f=>f.type==='phase'));assert(Number.isFinite(save.battleHistory[0].cashChange));
 await page.locator('#proBattleHistory button').filter({hasText:'新機能デモ：選択と段階変化'}).first().evaluate(e=>e.click());assert(await page.locator('#proBattleHistory input[type=range]').count());
 assert.equal(errors.length,0,errors.join('\n'));assert.equal(alerts.length,0,alerts.join('\n'));console.log('PASS: Chromium mobile boot, import/export, undo/redo, checkpoints, shared isolation, phase/event editors, live battle, campaign flags and replay');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
